-- MySQL Script generated by MySQL Workbench
-- Fri Jul 30 17:24:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Bank` ;

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bank` DEFAULT CHARACTER SET utf8 ;
USE `Bank` ;

-- -----------------------------------------------------
-- Table `Bank`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`User` ;

CREATE TABLE IF NOT EXISTS `Bank`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NULL,
  `birthday` DATE NULL,
  `fullName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`Account` ;

CREATE TABLE IF NOT EXISTS `Bank`.`Account` (
  `id` INT NOT NULL,
  `balance` FLOAT NULL,
  `withdrawLimit` FLOAT NULL,
  `numbAccount` INT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Account_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `Bank`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
